"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 4000
format = "[⚡](fg:yellow) [krissh](fg:purple) at $all"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[line_break]
disabled = true

[git_branch]
symbol = ' '
only_attached = true

[directory]
format = '[[$read_only](fg:124)$truncation_symbol$path](fg:cyan) '
home_symbol = " "
truncation_symbol = ' '
truncation_length = 2
read_only = '󱪨 '

[directory.substitutions]
"Documents" = "󰧮 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
" /dev" = " "
"Movies" = " "
" /work" = " "
".config" = "󰢻"
"dotfiles" = "󰢻 dotfiles"
"lib/" = ' lib'
"/lib/" = ' lib'
" /lib" = ' lib'
"node_modules" = ' node_modules'

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
style = 'green'
format = '[󰜘 $hash$tag ]($style)'
tag_symbol = " |  "

[git_status]
ahead = '[⇡${count}](lavender) '
behind = '⇣${count} '
conflicted = '󱡷 '
deleted = '󱀷 ${count} '
diverged = '⇡${ahead_count} ⇣${behind_count} '
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind)]($style)"
modified = '[ ${count}](peach) '
renamed = ' '
staged = '[+$count](green) '
stashed = " ${count} "
style = "red"
untracked = "[ ${count}](sapphire) "
up_to_date = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold red"
rebase = "󱓍 REBASING"
merge = " MERGING"
revert = "󰕍 REVERTING"
cherry_pick = ' CHERRY-PICKING'

[git_metrics]
disabled = true
format = '| [+$added](green) [-$deleted](124) '
only_nonzero_diffs = true

[battery]
full_symbol = '󰁹'
charging_symbol = '󱐥'
format = "[has $symbol $percentage]($style) "

[[battery.display]]
threshold = 30
discharging_symbol = '󰁼'
charging_symbol = '󱐥'
style = 'bold red'

[[battery.display]]
threshold = 20
discharging_symbol = '󰂃'
charging_symbol = '󱐥'
style = 'bold red'

[[battery.display]]
threshold = 40
style = 'bold yellow'
discharging_symbol = '󰁽'
charging_symbol = '󱐥'

[nodejs]
detect_folders = []

[package]
disabled = true
